---
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tailwindcss"
    groups:
      all-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
