---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tailwindcss"
    groups:
      all-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
